server:
  port: 8781

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

product-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

spring:
  application:
    name: order-service
